### ISSUE TITLE
hot reload not working?

### ISSUE THREAD

**Issue by bananaturtlesandwich** [Noxmore/bevy_trenchbroom#3]
basically what it says
i have the `file_watcher` feature enabled and getting the message `2024-05-11T18:48:49.171037Z  INFO bevy_asset::server: Reloading maps\startup.map because it has changed` when the file gets saved but the brushes don't get reloaded?

**Comment by Noxmore** [comment]
Whoops!
I knew this was a problem, but because of my scattered development habits (that i really should stop with) i forgot about it, and didn't end up fixing it.

Should be fixed in 0.3.0, which i just released.
