### ISSUE TITLE
grouped objects

### ISSUE THREAD

**Issue by bananaturtlesandwich** [Noxmore/bevy_trenchbroom#4]
grouped objects aren't loaded

**Comment by Noxmore** [comment]
I wasn't able to recreate this, could you be a bit more specific?

If my memory serves me, I do know that grouped objects in TrenchBroom use a `func_group` entity, which while not important for spawning grouped point entities, you do have to define yourself for grouped brushes to work. Maybe you forgot to define it?

**Comment by bananaturtlesandwich** [comment]
oh yeah works just fine if you define func_group the same way as world spawn - thx!
