### ISSUE TITLE
phong/smooth shading?

### ISSUE THREAD

**Issue by iBoonie** [Noxmore/bevy_trenchbroom#5]
Ive been playing around with this, its quite awesome!

Are there any plans to implement some kind of smooth shading (if its even possible)?
![u5OvS](https://github.com/Noxmore/bevy_trenchbroom/assets/62844047/9ad11eed-2f70-4a33-856c-7fbad052fb18)

**Comment by Noxmore** [comment]
Thank you, and yes! Thank you for reminding me!
Right now the plan is for this to be a function in BrushSpawnSettings, where you can specify the angle threshold to smooth the normals, Blender-style.

**Comment by Noxmore** [comment]
Well that took longer than expected.
Forgot to add "Fixes (ISSUE)" in my commit, so I'm closing it here.
