### ISSUE TITLE
Generated mesh differs on run, loses faces

### ISSUE THREAD

**Issue by iBoonie** [Noxmore/bevy_trenchbroom#8]
Started happening on last release. Was using the new `smooth_by_default_angle`, but it happens when you don't as well. The more brushes, the more often it happens.
Minimal example, just rename the file extension (doesn't need textures, but it still happens with them as well)
[example.map.txt](https://github.com/user-attachments/files/16277982/example.map.txt)

[2024-07-17 22-04-30.webm](https://github.com/user-attachments/assets/9bca08ea-9c85-4912-ba4c-d518aac7c0e6)

[2024-07-17 21-15-31.webm](https://github.com/user-attachments/assets/72510e85-2861-4a09-94c2-32b066dda749)

**Comment by Noxmore** [comment]
It was a simple mistake i really should've caught in testing, I'm still quite new at maintaining a project like this.
Still, thank you for taking the time to report this!
